# 기초데이터과학 (01분반)

## 03-1. 데이터 가공: pandas 활용

### Acknowledgement
#### 이 자료는 다음 서적의 내용을 바탕으로 작성되었음

- 파이썬 라이브러리를 활용한 데이터 분석. 한빛미디어
- 쉽게 배우는 파이썬 데이터 분석. 이지스 퍼블리싱

#### NumPy 배열 예제
실습에서 사용한 가상의 성적 데이터를 저장한 배열을 다시 살펴보자 

In [2]:
import numpy as np
import pandas as pd

subjects = ["과목A", "과목B", "과목C", "과목D"]

scores = np.array([[85, 72, 90, 68],
                   [92, 88, 95, 91],
                   [45, 58, 62, 40],
                   [78, 95, 71, 83],
                   [88, 81, 84, 90],
                   [60, 47, 55, 72],
                   [95, 69, 78, 66],
                   [70, 90, 88, 59]])

print(scores)

[[85 72 90 68]
 [92 88 95 91]
 [45 58 62 40]
 [78 95 71 83]
 [88 81 84 90]
 [60 47 55 72]
 [95 69 78 66]
 [70 90 88 59]]


- 3번 학생의 과목C 점수를 출력하고 싶다면 어떻게 해야할까?

























In [63]:
print("3번 학생의 과목C 점수:", scores[3, 2])

3번 학생의 과목C 점수: 71


- NumPy 배열에서는 행과 열을 **번호로만** 지칭할 수 있음
- `scores[3, 2]` 가 무엇을 뜻하는지 알려면 데이터 설명을 따로 찾아봐야함
- 열의 순서가 바뀌면 코드가 틀린 값을 내놓게 됨

같은 데이터를 pandas의 DataFrame으로 만들어 보자

In [4]:
df = pd.DataFrame(scores,
                  columns=["과목A", "과목B", "과목C", "과목D"],
                  index=["학생" + str(i) for i in range(8)])
df

,과목A,과목B,과목C,과목D
학생0,85,72,90,68
학생1,92,88,95,91
학생2,45,58,62,40
학생3,78,95,71,83
학생4,88,81,84,90
학생5,60,47,55,72
학생6,95,69,78,66
학생7,70,90,88,59


In [5]:
# 번호가 아니라 이름으로 지칭할 수 있다
print(df["과목C"])
print()
print("과목별 평균:")
print(df.mean())

학생0    90
학생1    95
학생2    62
학생3    71
학생4    84
학생5    55
학생6    78
학생7    88
Name: 과목C, dtype: int64

과목별 평균:
과목A    76.625
과목B    75.000
과목C    77.875
과목D    71.125
dtype: float64


- 값은 똑같지만 **행과 열에 이름표가 붙음**
- `scores[:, 2]` 대신 `df["과목C"]` 라고 쓸 수 있음
- 통계 함수도 결과에 이름이 함께 남음

**pandas의 DataFrame은 NumPy 배열에 이름표를 붙인 것**이라고 이해할 수 있음

### pandas
- 고수준의 자료구조와 파이썬에서 빠르고 쉽게 사용할 수 있는 데이터 분석 도구를 포함하는 라이브러리
  - 다른 산술 계산 도구인 NumPy와 SciPy, 분석 라이브러리인 statsmodels와 scikit-learn, 시각화 도구인 matplotlib과 함께 많이 사용
- NumPy의 배열 기반 계산 스타일을 많이 차용
  - for 문을 사용하지 않고 데이터를 처리하는 것
  - 배열 기반의 함수를 제공하는 것 등
- NumPy와 차이점
  - pandas는 표 형식의 데이터나 다양한 형태의 데이터를 다루는데 초점을 맞춰 설계됨
  - NumPy는 단일 배열 데이터를 다루는데 특화됨

In [6]:
import numpy as np
import pandas as pd
from pandas import Series, DataFrame

### pandas 데이터 구조
- Series
  - 일련의 객체를 담을 수 있는 1차원 배열 같은 데이터 구조
- DataFrame
  - 표 같은 형식의 데이터 구조

#### Series

In [10]:
obj = pd.Series([4, 7, -5, 3])


- 어떤 NumPy 자료형이라도 담을 수 있음
- 배열의 데이터와 연관된 이름을 붙일 수 있는 index 속성을 가짐
  - 데이터의 index를 지정하지 않으면 기본 인덱스로 정수 0에서 N-1(N은 데이터의 길이)까지 숫자로 지정
- 배열 데이터는 values 속성으로 액세스 가능
- Series 객체 생성
  - 간단하게는 배열 데이터로 생성 가능

In [11]:
print(obj)

0    4
1    7
2   -5
3    3
dtype: int64


- Series 객체를 출력했을 때 왼쪽은 인덱스, 오른쪽의 그에 해당하는 값을 표현

In [12]:
# values 속성으로 배열 데이터를 액세스할 수 있음
obj.values

#print(obj.values)

[ 4  7 -5  3]


In [14]:
# index 속성으로 인덱스를 확인할 수 있음
obj.index

#print(obj.index)

RangeIndex(start=0, stop=4, step=1)

- 각각의 데이터를 지칭하는 인덱스를 지정하여 Series 객체를 생성하는 경우

In [15]:
obj2 = pd.Series([4,7,-5,3], index=['d','b','a','c'])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [16]:
obj2.index

Index(['d', 'b', 'a', 'c'], dtype='object')

In [19]:
obj2['a']

#print(obj2['a'])

-5


In [13]:
obj2[['c','a','d']] # ['c','a','d']는 인덱스의 배열

c    3
a   -5
d    4
dtype: int64

In [14]:
obj2[1:4] # 리스트의 슬라이싱 연산과 유사

b    7
a   -5
c    3
dtype: int64

- 인덱스-값 연결은 불리언 배열을 사용해서 값을 걸러 내거나 산술 곱셈을 수행하거나 또는 수학 함수를 적용하는 등 NumPy 연산을 수행해도 유지됨

  - 불리언 배열을 이용해 값을 걸러 내는 예제

In [24]:
obj2[obj2 > 0] 

#print(obj2[obj2 > 0]) 

d    4
b    7
c    3
dtype: int64

In [26]:
obj2 > 0

#print(obj2 > 0)

d     True
b     True
a    False
c     True
dtype: bool

- 산술 연산 및 함수 적용 예제

In [22]:
obj2 * 2

#print(obj2 * 2)

d     8
b    14
a   -10
c     6
dtype: int64


In [27]:
np.exp(obj2)

d      54.598150
b    1096.633158
a       0.006738
c      20.085537
dtype: float64

- Series 객체는 고정 길이의 정렬된 dictionary라고 볼 수 있음
  - 인덱스 값에 데이터 값을 매핑하고 있으므로 dictionary와 비슷
  - Series 객체는 파이썬의 dictionary 객체를 인자로 받아야 하는 함수에서 이를 대체하여 사용할 수 있음
- 파이썬 dictionary 객체를 이용하여 Series 객체를 생성할 수 있음
  - dictionary의 키 값이 Series의 인덱스 값이 됨

In [28]:
sdata = {'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}
obj3 = pd.Series(sdata)
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

#### [예측] 실행하기 전에 생각해 볼 것

- `sdata`에는 Ohio, Texas, Oregon, Utah 네 개의 값이 들어 있음
- 그런데 인덱스로 넘기는 `states`는 California, Ohio, Oregon, Texas 임
- **`sdata`에 없는 California 자리에는 무엇이 들어갈까?**
- **`states`에 없는 Utah 값은 어떻게 될까?**


In [ ]:
# 인덱스를 직접 지정하고 싶다면 원하는 순서대로 인덱스를 직접 넘겨줄 수도 있음

states = ['California', 'Ohio', 'Oregon', 'Texas']

obj4 = pd.Series(sdata, index = states)
obj4

- sdata의 값 중 3개만 들어감, 'California'에 대한 값은 없기 때문에 NaN으로 표시됨
  - NaN은 pandas에서 누락된 값 혹은 NA 값으로 취급됨
- Utah에 대한 값은 인덱스로 사용한 states 배열에 포함되어 있지 않으므로 결과에 포함되지 않음

- pandas의 isnull, notnull 함수
  - 누락된 데이터를 찾을 때 사용

In [31]:
pd.isnull(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [32]:
obj4.isnull()

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [33]:
obj4['California'] = 43000 # 인덱스를 이용하여 새로운 값을 할당할 수 있음
obj4

California    43000.0
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

- items() 메소드
  - Series 객체에 있는 요소를 튜플 형태, (index, value)로 반환함

In [26]:
for i, v in obj4.items():
    print('%s : %d' %(i,v))

California : 43000
Ohio : 35000
Oregon : 16000
Texas : 71000


- Series 객체의 덧셈 연산

In [34]:
import pandas as pd

# A, B, C, D 네 회사의 1차년도 매출액과 2차년도 매출액이 주어졌다고 가정

sales = {'A': 5000000, 'B': 7100000, 'C': 3600000, 'D': 4050000}
year1 = pd.Series(sales)

year2 = pd.Series([3500000, 5500000, 4000000, 6000000], index=['B','D','C','A'])

print("year1 :")
print(year1)
print()
print("year2 :")
print(year2)

year1 :
A    5000000
B    7100000
C    3600000
D    4050000
dtype: int64

year2 :
B    3500000
D    5500000
C    4000000
A    6000000
dtype: int64


#### [예측] 실행하기 전에 생각해 볼 것

- `year1`은 **A, B, C, D 순서**이고 `year2`는 **B, D, C, A 순서**임
- 두 Series를 그냥 `year1 + year2` 로 더하면 어떤 결과가 나올까?

  1. 순서대로 위에서부터 더해진다 (A+B, B+D, C+C, D+A)
  2. 같은 이름끼리 찾아서 더해진다 (A+A, B+B, C+C, D+D)
  3. 순서가 달라서 오류가 난다

- NumPy 배열이었다면 어떻게 되었을지도 함께 생각해 볼 것



In [ ]:
total = year1 + year2
print(total)

- 기본적인 통계 함수
  - sum(), mean(), median(), var(), std(), count(), max(), min(), argmax(), argmin()

In [ ]:
print('네 회사의 2년간 매출액 합계: ', total.sum())
print('네 회사의 2년간 매출액 평균: ', total.mean())
print('네 회사의 2년간 매출액 최대값: ', total.max())
print('네 회사의 2년간 매출액 최소값: ', total.min())
print('2년간 매출액 최대값의 인덱스 번호: ', total.argmax())
print('2년간 매출액이 가장 많은 회사: ', total.index[total.argmax()])
print('2년간 매출액 최소값의 인덱스 번호: ', total.argmin())
print('2년간 매출액이 가장 적은 회사: ', total.index[total.argmin()])

# idxmax(), idxmin() 는 위치 대신 인덱스 이름을 바로 돌려줌
print()
print('idxmax()로 구한 매출액 1위 회사: ', total.idxmax())
print('idxmin()로 구한 매출액 최하위 회사: ', total.idxmin())

#### DataFrame
- 표와 같은 자료 구조
- 여러 개의 행(row)과 열(column)로 구성됨
  - 각 열은 서로 다른 종류의 값(숫자, 문자열, 불리언 등)을 담을 수 있음
- 행과 열에 대한 인덱스를 가지고 있음

- DataFrame 객체 생성
  - dictinary의 key, value 중 value에 리스트를 사용

In [37]:
import pandas as pd

data = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'],
        'year': [2000, 2001, 2002, 2001, 2002, 2003],
        'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

,state,year,pop
0,Ohio,2000,1.5
1,Ohio,2001,1.7
2,Ohio,2002,3.6
3,Nevada,2001,2.4
4,Nevada,2002,2.9
5,Nevada,2003,3.2


- 원하는 열의 순서로 DataFrame 객체 생성 가능

In [38]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop']) # columns 변수 값 설정
frame2

,year,state,pop
0,2000,Ohio,1.5
1,2001,Ohio,1.7
2,2002,Ohio,3.6
3,2001,Nevada,2.4
4,2002,Nevada,2.9
5,2003,Nevada,3.2


- 행에 대한 인덱스는 index 변수, 열에 대한 인덱스는 columns 변수로 설정

In [39]:
frame2 = pd.DataFrame(data, columns=['year', 'state', 'pop', 'debt'],
                      index=['one', 'two', 'three', 'four', 'five', 'six']) 

frame2

,year,state,pop,debt
one,2000,Ohio,1.5,NaN
two,2001,Ohio,1.7,NaN
three,2002,Ohio,3.6,NaN
four,2001,Nevada,2.4,NaN
five,2002,Nevada,2.9,NaN
six,2003,Nevada,3.2,NaN


- 열에 대한 인덱스로 해당 열에 대한 데이터만 추출

In [40]:
frame2['state'] 

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

In [41]:
frame2.state # 위와 동일. 열의 값을 속성처럼 이용

one        Ohio
two        Ohio
three      Ohio
four     Nevada
five     Nevada
six      Nevada
Name: state, dtype: object

- 여러 개의 열을 한 번에 추출하려면 **열 이름을 리스트로 묶어서** 전달
  - Series에서 `obj2[['c','a','d']]` 로 여러 값을 꺼낸 것과 같은 방식
  - 리스트에 적은 **순서대로** 열이 배치되므로 열 순서를 바꿀 때도 사용 가능

In [ ]:
frame2[['state', 'year']]   # 대괄호 두 겹 - 열 이름 리스트를 전달

- **대괄호가 한 겹이면 Series, 두 겹이면 DataFrame**

| 코드 | 결과 | 형태 |
|---|---|---|
| `frame2['state']` | 열 하나 | Series (1차원) |
| `frame2[['state']]` | 열 하나 | DataFrame (2차원) |
| `frame2[['state', 'year']]` | 열 두 개 | DataFrame (2차원) |

- 아래 셀로 직접 확인해 볼 것

In [ ]:
print(type(frame2['state']))
print(type(frame2[['state']]))
print()
print("한 겹:", frame2['state'].shape)
print("두 겹:", frame2[['state']].shape)

- 열 인덱스로 스칼라 값 할당 가능

In [42]:
frame2['debt'] = 16.5 
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,16.5
two,2001,Ohio,1.7,16.5
three,2002,Ohio,3.6,16.5
four,2001,Nevada,2.4,16.5
five,2002,Nevada,2.9,16.5
six,2003,Nevada,3.2,16.5


- 열 인덱스로 배열 값 할당 가능

In [43]:
import numpy as np

frame2['debt'] = np.arange(6.) 
frame2

,year,state,pop,debt
one,2000,Ohio,1.5,0.0
two,2001,Ohio,1.7,1.0
three,2002,Ohio,3.6,2.0
four,2001,Nevada,2.4,3.0
five,2002,Nevada,2.9,4.0
six,2003,Nevada,3.2,5.0


- 열 인덱스로 Series 객체 할당 가능
  - DataFrame의 인덱스에 맞춰 값이 할당되며 존재하지 않는 인덱스에는 누락값으로 할당

In [44]:
val = pd.Series([-1.2, -1.5, -1.7], index=['two', 'four', 'five'])
val

two    -1.2
four   -1.5
five   -1.7
dtype: float64

#### [예측] 실행하기 전에 생각해 볼 것

- `frame2`의 행 인덱스는 one ~ six 로 **여섯 개**임
- 그런데 지금 할당하려는 `val`에는 two, four, five **세 개**의 값밖에 없음
- `frame2['debt'] = val` 을 실행하면 나머지 세 행의 debt 값은 어떻게 될까?
- 값이 채워지는 **순서**는 무엇을 기준으로 정해질까?


In [ ]:
frame2['debt'] = val
frame2

### 데이터 파악하기
- 데이터가 주어졌을 때 먼저 하는 일은 데이터의 전반적인 구조를 파악하는 것
  - 어떤 변수들이 있는가? 몇 행으로 구성되는가? 등을 살펴보면서 데이터의 특징에 대한 감을 잡을 수 있음

- 데이터를 파악할 때 사용하는 함수
  - head(): 앞부분 출력
  - tail(): 뒷부분 출력
  - shape : 행, 열 개수 출력
  - info(): 변수 속성 출력
  - describe(): 요약 통계량 출력 


In [58]:
import pandas as pd

# pandas의 read_csv() 함수: csv 파일을 읽어서 DataFrame 객체를 생성
# 파일이 같은 폴더에 있으면 아래 줄을 사용
exam = pd.read_csv('exam.csv')

# Colab 등에서 파일을 올리기 어려우면 아래 두 줄의 주석을 해제하여 사용
#url = 'https://raw.githubusercontent.com/skang-koreatech/BasicDataScience_2026-2/main/exam.csv'
#exam = pd.read_csv(url) 

- head(): 데이터 앞부분 확인하기

In [60]:
exam.head()      # 데이터의 처음 5행 출력
exam.head(10)    # 괄호에 숫자를 입력하면 해당 행까지 출력

,id,nclass,math,english,science
0,1,1,50,98,50
1,2,1,60,97,60
2,3,1,45,86,78
3,4,1,30,98,58
4,5,2,25,80,65
5,6,2,50,89,98
6,7,2,80,90,45
7,8,2,90,78,25
8,9,3,20,98,15
9,10,3,50,98,45


- tail(): 데이터 뒷부분 확인하기

In [48]:
exam.tail()      # 데이터의 마지막 5행 출력
exam.tail(10)    # 뒤에서 10행까지 출력

,id,nclass,math,english,science
10,11,3,65,65,65
11,12,3,45,85,32
12,13,4,46,98,65
13,14,4,48,87,12
14,15,4,75,56,78
15,16,4,58,98,65
16,17,5,65,68,98
17,18,5,80,78,90
18,19,5,89,68,87
19,20,5,78,83,58


- shape: 데이터가 몇 행, 몇 열로 구성되는지 알아보기

In [49]:
exam.shape # shape은 함수가 아니라 DataFrame의 속성임

(20, 5)

- info(): 변수 속성 파악하기

In [50]:
exam.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   id       20 non-null     int64
 1   nclass   20 non-null     int64
 2   math     20 non-null     int64
 3   english  20 non-null     int64
 4   science  20 non-null     int64
dtypes: int64(5)
memory usage: 932.0 bytes


- describe(): 요약 통계량 구하기

In [51]:
exam.describe()

,id,nclass,math,english,science
count,20.00000,20.000000,20.000000,20.000000,20.000000
mean,10.50000,3.000000,57.450000,84.900000,59.450000
std,5.91608,1.450953,20.299015,12.875517,25.292968
min,1.00000,1.000000,20.000000,56.000000,12.000000
25%,5.75000,2.000000,45.750000,78.000000,45.000000
50%,10.50000,3.000000,54.000000,86.500000,62.500000
75%,15.25000,4.000000,75.750000,98.000000,78.000000
max,20.00000,5.000000,90.000000,98.000000,98.000000


### 변수명 바꾸기
- 변수명이 복잡하거나 기억하기 어려운 문자로 되어 있는 경우 쉬운 단어로 변경하면 데이터를 다루기 수월해짐

- DataFrame의 rename() 함수 이용

In [52]:
# 데이터 프레임 만들기

df_raw = pd.DataFrame({'var1': [1,2,1],
                       'var2': [2,3,2]})
df_raw

,var1,var2
0,1,2
1,2,3
2,1,2


In [53]:
# 데이터 프레임 복사본 만들기

df_new = df_raw.copy()

df_new

,var1,var2
0,1,2
1,2,3
2,1,2


- 데이터를 변형하는 작업을 할 때는 원본을 직접 사용하기보다 복사본을 만들어 사용하는 것이 바람직함
  - 작업 중 오류가 발생하더라도 원 상태로 복구 가능
  - 데이터를 비교하면서 변형되는 과정 검토 가능

In [54]:
# 변수명 바꾸기

df_new = df_new.rename(columns = {'var2': 'v2'}) # var2를 v2로 수정

df_new

,var1,v2
0,1,2
1,2,3
2,1,2


### 파생 변수 만들기
- 데이터에 들어 있는 변수만 이용해 분석할 수도 있지만, 변수를 조합하거나 새 변수를 만들어 분석하는 것도 가능
  - 예를 들어 여러 과목의 시험 점수를 조합해 전과목 평균 점수를 나타내는 변수를 만들어 분석할 수 있음
  - 기존의 변수를 변형해 만든 변수를 파생 변수라고 함

In [3]:
df = pd.DataFrame({'var1': [4,3,8],
                  'var2': [2,6,1]})
df

,var1,var2
0,4,2
1,3,6
2,8,1


- var1과 var2 변수의 값을 더한 var_sum이라는 파생 변수를 만들어 df에 추가하기

In [4]:
df['var_sum'] = df['var1'] + df['var2']

df

,var1,var2,var_sum
0,4,2,6
1,3,6,9
2,8,1,9


- var1과 var2 변수의 평균을 계산하여 var_mean이라는 파생 변수를 만들어 df에 추가하기

In [5]:
df['var_mean'] = (df['var1'] + df['var2']) / 2

df

,var1,var2,var_sum,var_mean
0,4,2,6,3.0
1,3,6,9,4.5
2,8,1,9,4.5


- 위 방식은 열이 두세 개일 때는 편하지만, **열이 많아지면 일일이 나열하기 어려움**
  - 예를 들어 과목이 7개라면 `df['A'] + df['B'] + ...` 로 일곱 번을 적어야 함
- 이때는 지난 시간 NumPy에서 배운 **`axis`** 를 그대로 사용 가능
  - `axis=1` : 열 방향으로 계산 -> **행(관측치)마다** 결과가 나옴
  - `axis=0` : 행 방향으로 계산 -> **열(변수)마다** 결과가 나옴
  - `axis` 를 생략하면 기본값은 `axis=0`

In [ ]:
# 앞에서 만든 파생 변수와 같은 결과를 axis 로 계산
df['var_sum2']  = df[['var1', 'var2']].sum(axis=1)
df['var_mean2'] = df[['var1', 'var2']].mean(axis=1)

df

- `var_sum` 과 `var_sum2`, `var_mean` 과 `var_mean2` 의 값이 동일함
- 열이 많아질수록 아래 방식이 훨씬 간결함

- 계산 대상 열을 `df[['var1', 'var2']]` 처럼 **명시적으로 골라 주는 것이 중요**
  - `df.sum(axis=1)` 로 전체를 쓰면 앞에서 만든 파생 변수(`var_sum` 등)까지 함께 더해짐
  - 오류는 나지 않고 값만 틀리게 나오므로 발견하기 어려움
- 아래 셀에서 그 차이를 확인해 볼 것

In [ ]:
print("계산할 열만 지정:")
print(df[['var1', 'var2']].sum(axis=1))
print()
print("전체를 대상으로 계산 (파생 변수까지 포함되어 값이 달라짐):")
print(df.sum(axis=1))

- `axis=0` 으로 계산하면 **변수(열)별** 결과가 나옴

In [ ]:
print("변수별 평균 (axis=0):")
print(df[['var1', 'var2']].mean(axis=0))

### 연습문제
위에서 사용한 exam.csv 파일을 읽어 DataFrame 객체를 생성하고 변수명을 변경하기
  - math를 math_score로 변경
  - english를 english_score로 변경
  - science를 science_score로 변경
  
math, english, science 점수의 평균을 계산하고 이를 mean_score 파생 변수로 만들어 DataFrame에 추가하기

In [61]:
import pandas as pd

# 파일이 같은 폴더에 있으면 아래 줄을 사용
exam = pd.read_csv('exam.csv')

# Colab 등에서 파일을 올리기 어려우면 아래 두 줄의 주석을 해제하여 사용
#url = 'https://raw.githubusercontent.com/skang-koreatech/BasicDataScience_2026-2/main/exam.csv'
#exam = pd.read_csv(url)

# 변수명 변경


# 평균 점수 파생 변수 만들기

