## 기초데이터과학 (01분반)

## Lab 01. NumPy 실습

각 문제의 코드 틀에서 `None` 으로 비어 있는 부분을 채워 완성하시오.
- `print` 문은 이미 작성되어 있으므로 수정하지 않아도 됨
- 셀을 실행한 결과가 아래 **기대 출력**과 같으면 정답

### 0. 실습 데이터

아래 셀을 먼저 실행할 것. 학생 8명의 4개 과목 성적표이다.
행은 학생, 열은 과목을 의미한다.

In [1]:
import numpy as np

subjects = ["과목A", "과목B", "과목C", "과목D"]

scores = np.array([[85, 72, 90, 68],
                   [92, 88, 95, 91],
                   [45, 58, 62, 40],
                   [78, 95, 71, 83],
                   [88, 81, 84, 90],
                   [60, 47, 55, 72],
                   [95, 69, 78, 66],
                   [70, 90, 88, 59]])

print(scores)

[[85 72 90 68]
 [92 88 95 91]
 [45 58 62 40]
 [78 95 71 83]
 [88 81 84 90]
 [60 47 55 72]
 [95 69 78 66]
 [70 90 88 59]]


### 1. 위 성적 배열의 기본 정보를 출력하고, 학생별 평균과 과목별 평균을 각각 구하는 코드를 작성하시오.

In [ ]:
import numpy as np

# 배열의 기본 정보
info_ndim  = None      # TODO - 차원
info_shape = None      # TODO - 형상
info_size  = None      # TODO - 크기

# 학생별 평균과 과목별 평균 - mean 함수에 axis 지정
# axis=0을 쓰면 행이 사라지고, axis=1을 쓰면 열이 사라진다는 점을 생각할 것
stu_mean = None        # TODO
sub_mean = None        # TODO

print("차원 수:", info_ndim)
print("형상:", info_shape)
print("원소 수:", info_size)
print("학생별 평균:", stu_mean, stu_mean.shape)
print("과목별 평균:", sub_mean, sub_mean.shape)

**기대 출력**

```
차원 수: 2
형상: (8, 4)
원소 수: 32
학생별 평균: [78.75 91.5  51.25 81.75 85.75 58.5  77.   76.75] (8,)
과목별 평균: [76.625 75.    77.875 71.125] (4,)
```

### 2. 각 과목에서 가장 높은 점수와 그 점수를 받은 학생의 번호를 출력하는 코드를 작성하시오.

In [ ]:
import numpy as np

# 과목별 최고점과 그 점수를 받은 학생의 번호(행 인덱스)
# max는 값을, argmax는 위치를 돌려준다는 점에 주의할 것
top_score = None       # TODO
top_idx   = None       # TODO

for j in range(4):
    print(f"{subjects[j]}: 최고점 {top_score[j]}점, {top_idx[j]}번 학생")

**기대 출력**

```
과목A: 최고점 95점, 6번 학생
과목B: 최고점 95점, 3번 학생
과목C: 최고점 95점, 1번 학생
과목D: 최고점 91점, 1번 학생
```

### 3. 모든 과목에서 80점 이상을 받은 학생이 몇 명인지 구하고, 해당 학생의 번호를 출력하는 코드를 작성하시오.

In [ ]:
import numpy as np

# 학생별 최저점 - min 함수에 axis 지정
# '모든 과목이 80점 이상'은 '가장 낮은 점수가 80점 이상'과 같다는 점을 이용할 것
stu_min = None         # TODO

# 학생별로 조건을 만족하는지 나타내는 True/False 배열
mask = None            # TODO

# 조건을 만족하는 학생 수 - True는 1, False는 0으로 취급됨
n_pass = None          # TODO

# 조건을 만족하는 학생의 번호 - numpy의 where 함수 사용
# where 함수는 조건이 True인 위치를 알려주는 용도로도 사용할 수 있음
pass_idx = None        # TODO

print("학생별 최저점:", stu_min)
print(mask)
print("전 과목 80점 이상:", n_pass, "명")
print("해당 학생 번호:", pass_idx)

**기대 출력**

```
학생별 최저점: [68 88 40 71 81 47 66 59]
[False  True False False  True False False False]
전 과목 80점 이상: 2 명
해당 학생 번호: [1 4]
```

### 4. 성적 배열에서 50점 미만인 점수만 추출하여 출력하고, 60점 미만인 점수를 모두 60점으로 올린 새 배열을 만드는 코드를 작성하시오. 단, 원본 배열은 그대로 유지해야 한다.

In [ ]:
import numpy as np

# 50점 미만인 점수만 추출 - 배열의 대괄호 안에 조건식을 넣는 방법 사용
low = None             # TODO

# 60점 미만을 60점으로 올린 새 배열 - numpy의 where 함수 사용
adjusted = None        # TODO

# 원본은 2차원인데 추출 결과는 몇 차원인지 확인해 볼 것
print("50점 미만:", low)
print("형상:", low.shape)
print("원본 최저점:", scores.min())
print("보정 후 최저점:", adjusted.min())

**기대 출력**

```
50점 미만: [45 40 47]
형상: (3,)
원본 최저점: 40
보정 후 최저점: 60
```

### 브로드캐스팅

지금까지는 같은 크기의 배열끼리만 연산했다.
NumPy는 **형상이 다른 배열끼리도** 연산할 수 있는데, 이를 **브로드캐스팅(broadcasting)** 이라고 한다.
작은 배열을 큰 배열의 형상에 맞게 퍼뜨린 뒤 계산하는 방식이다.

In [1]:
a = np.array([[1, 2, 3],
              [4, 5, 6]])          # (2, 3)

b = np.array([10, 20, 30])         # (3,)    - 되는 경우 1
c = np.array([10, 20])             # (2,)    - 안 되는 경우
d = np.array([[10],
              [20]])               # (2, 1)  - 되는 경우 2

print("a + b  형상", a.shape, "+", b.shape)
print(a + b, "\n")

try:
    print(a + c)
except ValueError as e:
    print("a + c  형상", a.shape, "+", c.shape, "-> 오류:", e, "\n")

print("a + d  형상", a.shape, "+", d.shape)
print(a + d)

a + b  형상 (2, 3) + (3,)
[[11 22 33]
 [14 25 36]] 

a + c  형상 (2, 3) + (2,) -> 오류: operands could not be broadcast together with shapes (2,3) (2,)  

a + d  형상 (2, 3) + (2, 1)
[[11 12 13]
 [24 25 26]]


#### 규칙

두 배열의 형상을 **오른쪽 끝부터** 한 자리씩 비교한다.
축의 개수가 다르면 **적은 쪽의 왼쪽에 1을 채워** 개수를 맞춘다.

각 자리에서 **두 크기가 같거나, 둘 중 하나가 1이면** 통과한다.
하나라도 어긋나면 오류이고, 결과의 형상은 각 자리에서 **큰 쪽**이 된다.

주의할 점은 **1만 늘어날 수 있다**는 것이다. 2와 4처럼 둘 다 1이 아니면 배수 관계여도 오류다.

#### 예제로 확인하기

`a`는 형상이 `(2, 3)`인 배열이다.

```
a = [[1, 2, 3],
     [4, 5, 6]]
```

**되는 경우 1** — `b = [10, 20, 30]`, 형상 `(3,)`

```
      2 x 3
      1 x 3     <- (3,) 은 왼쪽에 1이 채워져 (1, 3) 이 된다
      -----
오른쪽 자리: 3 = 3  통과
다음 자리  : 2 vs 1  ->  1이 2로 늘어남  통과
결과: (2, 3)
```

**안 되는 경우** — `c = [10, 20]`, 형상 `(2,)`

```
      2 x 3
      1 x 2     <- (2,) 는 (1, 2) 가 된다
      -----
오른쪽 자리: 3 vs 2  ->  다르고 둘 다 1이 아님   오류
```

"2와 2가 맞으니 될 것 같다"고 생각하기 쉽지만, 비교는 **왼쪽이 아니라 오른쪽 끝부터** 시작한다.

**되는 경우 2** — `d = [[10], [20]]`, 형상 `(2, 1)`

```
      2 x 3
      2 x 1
      -----
오른쪽 자리: 3 vs 1  ->  1이 3으로 늘어남  통과
다음 자리  : 2 = 2   통과
결과: (2, 3)
```

같은 값 `[10, 20]` 이라도 `(2,)` 는 실패하고 `(2, 1)` 로 바꾸면 성공한다.
`reshape(-1, 1)` 을 쓰는 이유가 바로 이것이다. (한 열짜리 세로 배열로 형상을 바꿈)

### 5. 과목마다 난이도가 다르므로 점수를 그대로 비교하기 어렵다. 각 점수를 해당 과목의 평균과 표준편차로 표준화(z-score)하는 코드를 작성하시오.

$$ z = \frac{x - \mu_{\text{과목}}}{\sigma_{\text{과목}}} $$

In [ ]:
import numpy as np

# 과목별 평균과 표준편차 - mean, std 함수에 axis 지정
mu    = None           # TODO
sigma = None           # TODO

# 표준화 - 반복문을 사용하지 말고 브로드캐스팅을 이용할 것
z = None               # TODO

print("과목별 평균:", mu.round(2))
print("과목별 표준편차:", sigma.round(2))
print("z 형상:", z.shape)
print(z[:3].round(3))
print("z의 과목별 평균:", z.mean(axis=0).round(6))
print("z의 과목별 표준편차:", z.std(axis=0).round(6))

**기대 출력**

```
과목별 평균: [76.62 75.   77.88 71.12]
과목별 표준편차: [16.19 15.6  13.24 15.99]
z 형상: (8, 4)
[[ 0.517 -0.192  0.916 -0.195]
 [ 0.95   0.833  1.293  1.243]
 [-1.954 -1.089 -1.199 -1.947]]
z의 과목별 평균: [ 0.  0.  0. -0.]
z의 과목별 표준편차: [1. 1. 1. 1.]
```